### PR TITLE
Un-endorse Steven Buss

### PR DESCRIPTION
**Pull request by MatrixFrog**
You suggested on twitter dot com: "if you don't think I should be endorsed, then submit a pull request!" [1] and I noticed there are zero open pull requests. So I thought, fuck it, let me try doing that and see what happens.

[1] https://twitter.com/sbuss/status/1222219882504183808

### CODE REVIEW

**Comment by mpancia** [comment]
Seconding this. As a tech worker, I don't want him representing me.

**Comment by KevinGarnettGaryMedel** [comment]
I second this motion

**Comment by pbilling** [comment]
I don't think you should be endorsed, Steven.

**Comment by jkvalentine** [comment]
yeah, i don't want this person representing me

**Comment by jimbattin** [comment]
I'm a technology worker and do not feel comfortable giving my endorsement to Steven Buss. However, as a compromise, I recommend as an industry we adopt the phrase "Buss Factor" to refer to situations where conflicts of interest are at play.

**Comment by jeffmay** [comment]
No thanks on yimbyism. I want a politician who understands class politics. We need good, mixed-income public housing, not developer handouts for profiteers to leach us dry.

**Comment by ArulselvanMadhavan** [comment]
+1

**Comment by kurtisnelson** [comment]
This PR does not have any tests and CI is not setup, what is the revert plan?

**Comment by mpancia** [comment]
> This PR does not have any tests and CI is not setup, what is the revert plan?

In this case, it seems like we're safe to just revert the commit if necessary, but I agree that this is a bit ad-hoc, and should be limited to a one-time fix. Filing an issue.

**Comment by tedivm** [comment]
I also think this endorsement should be removed. I have major concerns about how Steven Buss has interacted with people online, and think it's inappropriate for him to both create this guide and essentially endorse himself.

**Pull request closed without merging**
